version: '3.7'
services:
  db:
    container_name: playground_db
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=main
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: